### ISSUE TITLE
Handling both write and execute commands as write.

### ISSUE THREAD

**Issue by lilezek** [telefonicaid/lwm2m-node-lib#71]
This code located at `lib/lwm2m-client.js:47`:

```javascript
function loadHandlers(serverInfo) {
    serverInfo.handlers = {
        write: {
            lib: require('./services/client/write').handle,
            user: coapRouter.defaultHandler
        },
        execute: {
            lib: require('./services/client/write').handle,
            user: coapRouter.defaultHandler
        },
        read: {
            lib: readService.handle,
            user: coapRouter.defaultHandler
        }
    };
}
```

is intended? 

After changing 

```javascript
       execute: {
            lib: require('./services/client/write').handle,
            user: coapRouter.defaultHandler
        },
```
to 

```javascript
       execute: {
            lib: require('./services/client/execute').handle,
            user: coapRouter.defaultHandler
        },
```
the client testing crashes trying to execute a command:

```
/home/***/Escritorio/lwm2m-node-lib/node_modules/async/lib/async.js:656
            return fn.apply(
                      ^
TypeError: Cannot call method 'apply' of undefined
    at /home/***/Escritorio/lwm2m-node-lib/node_modules/async/lib/async.js:656:23
    at fn (/home/***/Escritorio/lwm2m-node-lib/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/***/Escritorio/lwm2m-node-lib/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by dmoranj** [comment]
It seems like a bug at first sight. I will try to check it to see if it makes any sense.
